#!/bin/bash
# Deploy catalog.beer to server
#
# Usage:
#   ./deploy.sh              Interactive mode (prompts for environment)
#   ./deploy.sh staging      Deploy to staging
#   ./deploy.sh production   Deploy to production
# Warn if there are uncommitted changes
if ! git diff --quiet HEAD 2>/dev/null; then
	echo "WARNING: You have uncommitted changes."
	git status --short
	echo ""
	if [[ -n "$1" ]]; then
		echo "Aborting non-interactive deploy due to uncommitted changes."
		exit 1
	fi
	read -p "Deploy anyway? (y/n): " confirm
	if [[ $confirm != "y" ]]; then
		echo "Aborted."
		exit 0
	fi
fi

# Determine environment
if [[ -n "$1" ]]; then
	# CLI argument mode
	ENV="$1"
else
	# Interactive mode
	echo "Deploy to which environment?"
	echo "  1) Staging"
	echo "  2) Production"
	read -p "Select (1 or 2): " choice
	case $choice in
		1) ENV="staging" ;;
		2) ENV="production" ;;
		*)
			echo "Invalid selection. Aborted."
			exit 1
			;;
	esac
fi

case $ENV in
	staging)
		HOST="172.236.249.199"
		DEST="staging.catalog.beer"
		echo "Deploying to Staging..."
		;;
	production)
		HOST="172.233.129.106"
		DEST="catalog.beer"
		if [[ -z "$1" ]]; then
			read -p "Are you sure you want to deploy to Production? (y/n): " confirm
			if [[ $confirm != "y" ]]; then
				echo "Aborted."
				exit 0
			fi
		fi
		echo "Deploying to Production..."
		;;
	*)
		echo "Unknown environment: $ENV"
		echo "Usage: $0 [staging|production]"
		exit 1
		;;
esac

REMOTE="michael@$HOST"
REMOTE_PATH="/var/www/html/$DEST/public_html"
SOCKET="/tmp/deploy-ssh-$$"

# Generate version file
DIRTY=false
if ! git diff --quiet HEAD 2>/dev/null; then
	DIRTY=true
fi
cat > config/version.php <<VEOF
<?php
// Generated by deploy.sh at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
define('VERSION_COMMIT', '$(git rev-parse HEAD)');
define('VERSION_COMMIT_SHORT', '$(git rev-parse --short HEAD)');
define('VERSION_BRANCH', '$(git rev-parse --abbrev-ref HEAD)');
define('VERSION_TIMESTAMP', '$(date -u '+%Y-%m-%d %H:%M:%S UTC')');
define('VERSION_DIRTY', $DIRTY);
?>
VEOF
echo "Generated config/version.php ($(git rev-parse --short HEAD))"

# Open a shared SSH connection to avoid multiple password prompts
ssh -fNM -S "$SOCKET" "$REMOTE"
trap 'ssh -S "$SOCKET" -O exit "$REMOTE" 2>/dev/null' EXIT

RSYNC_OUTPUT=$(rsync -azOi --no-perms --delete \
	-e "ssh -S '$SOCKET'" \
	--exclude '.git' \
	--exclude '.claude' \
    --exclude '.editorconfig' \
	--exclude '.nova' \
	--exclude '.gitignore' \
	--exclude '.gitattributes' \
	--exclude '.DS_Store' \
	--exclude 'CLAUDE.md' \
	--exclude 'deploy.sh' \
	--exclude '*.sql' \
	--exclude 'maintenance.html' \
	--exclude 'README.md' \
	--exclude 'sitemap*.xml' \
	--exclude '*.p8' \
	--exclude 'php-errors-*.txt' \
	--filter 'P classes/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer/***' \
	./ "$REMOTE:$REMOTE_PATH/" 2>&1)

RSYNC_STATUS=$?

if [ "$RSYNC_STATUS" -ne 0 ]; then
	echo "rsync FAILED (exit $RSYNC_STATUS):"
	echo "$RSYNC_OUTPUT"
	exit "$RSYNC_STATUS"
fi

# Parse rsync --itemize-changes output. Works on GPL rsync 3+, rsync 2.6.9, and
# Apple's openrsync. Each interesting line begins with an 11-char itemize string:
#   >f.......... filename   (file being transferred to remote)
#   *deleting    filename   (file being deleted on remote)
#   .d..t...... ./          (unchanged directory — skip)
TRANSFERRED=$(echo "$RSYNC_OUTPUT" | awk '
	/^[<>]f/ { sub(/^[^ ]+ +/, ""); if ($0 !~ /\/$/) print }
')
DELETED=$(echo "$RSYNC_OUTPUT" | awk '
	/^\*deleting/ { sub(/^\*deleting +/, ""); if ($0 !~ /\/$/) print }
')

TRANSFER_COUNT=$(echo -n "$TRANSFERRED" | grep -c . || true)
DELETE_COUNT=$(echo -n "$DELETED" | grep -c . || true)

if [ "$TRANSFER_COUNT" -gt 0 ]; then
	echo "Transferred $TRANSFER_COUNT files:"
	echo "$TRANSFERRED"
fi
if [ "$DELETE_COUNT" -gt 0 ]; then
	echo "Deleted $DELETE_COUNT files:"
	echo "$DELETED"
fi
if [ "$TRANSFER_COUNT" -eq 0 ] && [ "$DELETE_COUNT" -eq 0 ]; then
	# Parser found nothing. If rsync produced any output beyond the headers,
	# surface it so silent reporting bugs don't lie about what happened.
	if [ -n "$RSYNC_OUTPUT" ]; then
		echo "No transfers/deletions parsed. Raw rsync output:"
		echo "$RSYNC_OUTPUT"
	else
		echo "No files changed."
	fi
fi

# Set ownership and permissions so Apache can read/serve and michael can deploy.
# config/passwords.php is locked down to 600 (owner-only) since it holds secrets.
ssh -S "$SOCKET" -t "$REMOTE" "sudo chown -R www-data:developers $REMOTE_PATH/ && sudo find $REMOTE_PATH/ -type d -exec chmod 2775 {} + && sudo find $REMOTE_PATH/ -type f -exec chmod 664 {} + && sudo chmod 600 $REMOTE_PATH/config/passwords.php"

echo "Deploy to $DEST complete."
